mozilla/pluotsorbet

tests/automation.js, tests/com/ibm/tck/client/TestRunner.java, tests/com/ibm/tck/javax/microedition/io/file/FileSystemRegistry/AddFileSystemListener.java, tests/com/ibm/tck/javax/microedition/io/file/FileSystemRegistry/ListRoots.java, tests/com/ibm/tck/javax/microedition/io/file/FileSystemRegistry/RemoveFileSystemListener.java, tests/fs/automation.js, tests/fs/fstests.html, tests/fs/fstests.js
This branch enables the FileConnection TCK unit tests in automation, excluding those tests that don't yet pass because we haven't implemented the functionality they test or because they require manual interaction.
=> enable FileConnection TCK tests in automation

index.js
I haven't tested this at all yet. I'm going to figure out how to do that next.
This is probably meant to fix #736.
=> Revoke video object URLs.

midp/gfx.js, tests/contacts.js
-allows running pim test in chrome
-fixes infinite loop in onerror
=> More fixes for chrome.

main.html, tests/fs/fstests.html, tests/fs/init-fs-v1.html, tests/fs/init-fs-v2.html, tests/fs/populate-fs-v2.html, tests/fs/test-fs-init.html, tests/fs/test-fs-populate.html, timer.js
Using `Promise` is little lighter than `postMessage`.
=> Reimplement setZeroTimeout with Promise.

java/custom/com/nokia/mid/ui/TextEditor.java, midp/frameanimator.js, midp/gfx.js
Makes scrolling screens less laggy.
=> Use UnimplementedNative to warn less.

midp/socket.js
This contains two simple optimizations for our socket handling code.
=> Misc socket optimizations

bindings.ts, context.ts, runtime.ts, tests/automation.js, tests/java/lang/TestThreadPriority.java
It is a simple thread scheduler to let the thread with higher priority run first.
=> Thread scheduler

runtime.ts
Within `processRunningQueue` `ctx.execute` is run which in turn calls `scheduleRunningContext` and schedules a timeout. Then further down within `processRunningQueue` it calls itself and schedules another timeout.
Fixes #945
=> Guard against scheduling thread processing multiple times.

context.ts, jit/baseline.ts, main.html, main.js, native.js, runtime.ts
Reverts andreasgal/j2me.js#955
=> Revert "Preempt threads." (fixes #960)

interpreter.ts, libs/long.js, types.ts
=> Thoroughly check return values.

midp/codec.js, midp/crypto.js, midp/localmsg.js, midp/media.js, midp/midp.js, midp/socket.js, native.js
This PR isn't modifying libs/fs.js because using a Int8Array instead of a Uint8Array causes a test failure (TestInputOutputStorage)
=> Use Int8Array instead of Uint8Array throughout the codebase

tests/RunTests.java
This will help @mbebenita figure out a test "failure" in #996, and it's also generally useful for diagnosing the class of failures to which that one belongs.
=> report known failures in unit tests

libs/console.js
Tired of re-adding this to my code all the time....
=> Add profile methods to console if available.

context.ts, interpreter.ts, main.html.in, midp/gfx.js, midp/midp.js, runtime.ts
Stop all the running thread and show the following waiting screen before the app window is closed:
=> Improve experience of exiting 

tests/RunTests.java
It'd be easier to find class failures if I could search for the text "class fail".
=> report class failures

tests/automation.js, tests/com/sun/midp/io/j2me/http/TestHttpConnection.java, tests/com/sun/midp/io/j2me/socket/StressTestSocket.java, tests/com/sun/midp/io/j2me/socket/TestSocket.java, tests/com/sun/midp/ssl/TestSSLStreamConnection.java, tests/javax/microedition/io/TestHttpsConnection.java
=> Enable socket tests

tools/package.sh
This fixes bustage from #1097.
=> package the vm/ dir

aot-methods.txt, java/custom/com/sun/cldc/i18n/j2me/UTF_8_Reader.java, java/custom/com/sun/cldc/i18n/j2me/UTF_8_Writer.java, native.js, tests/com/sun/cldc/i18n/TestUtfReaders.java
@marco-c, @mbebenita: This reverts just the UTF_8_Writer and UTF_8_Reader changes from #996 to fix #1149.  It doesn't work yet; unsure why.
=> revert UTF_8_* changes from #996 (fixes #1149)

interpreter.ts
In spider monkey shell this disables optimizations.
=> Remove debugger statement.

interpreter.ts, jit/baseline.ts, util.js, vm/runtime.ts
Sitting around in stash for awhile...Now all methods in classes.jar can compile (one whole more method!) and one more method in a midlet.
=> Add baseline jit for new multi array.

main.html.in, polyfill/canvas-toblob.js
From https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob.
=> polyfill Canvas.toBlob for Chrome

midp/midp.js
=> Add dummy native implementation for GestureInteractiveZone.getGestures.

bytecodes.ts, jit/baseline.ts
This PR reduces the number of stack assignments generated by the baseline compiler fixing #1155
=> Reify Stack

benchmark.js
This branch adds *start* and *buildBaseline* methods to the Benchmark module, which is helpful for running startup benchmarks from the Web Console.
=> expose methods for starting startup benchmark and building baseline

tests/RunTests.java, tests/automation.js
I find myself adding this locally to be able to quickly determine which
test is timing out.
=> Print running test name

jit/analyze.ts
Removes roughly ~150 unwinds from classes.jar.js
=> Check if a class is final in the statically bound check.

index.js.in, jit/analyze.ts, midp/media.js
AMR audio could only be played with privileged app on Firefox OS device. In order to support this kind of audio, I have to move the audio playing code from main.html to index.html.
=> Playing audio in parent window to gain the privilege to play AMR audio on Firefox OS device

libs/fs.js, midp/fs.js
Commit 1:
My FS ends up in a bad state occasionally on chrome, not sure if it happens in firefox since the break on errors is always reliable in the debugger. I've added some logging so we can hopefully see this if it does happen.
Commit 2:
Chrome seems to have problems exporting empty blobs.
=> More error reporting for the FS.

index.js.in
=> Fix typo in index.js.in

midp/midp.js
They're unneeded since we're relying on the Firefox OS security model (or web security model).
=> Remove unneeded Permissions native implementations

libs/console.js
It was introduced by commit 9941d5a53b87f08dc0031ba704b4ead633dd4308.
=> Fixed regression: console output filters is broken.

main.js, shumway/profiler/timelineFrame.ts
This PR prints aggregated profiling stats followed by detailed events. It also filters out events whose elapsed time is under a certain threshold.
=> Collect profiling stats.

bench/SystemOutBench.java
This adds a benchmark for *System.out.println* and *System.out.print*, which print characters to the console one at a time.
=> add benchmark for System.out.print(ln)

Makefile
Follow up for https://github.com/mozilla/j2me.js/pull/1302
=> Remove bld directory on make clean

README.md
=> Update readme with the latest profiling notes.

midp/gfx.js
A warning: I was unable to run the tests -- some kind of Python exception -- so I haven't been able to test that strings containing emoji work correctly.
=> Optimize drawString

java/custom/com/nokia/mid/s40/bg/BGUtils.java, java/custom/com/sun/midp/main/AmsUtil.java, midp/background.js, midp/localmsg.js, tests/midlets/background/BackgroundMIDlet1.java, tests/midlets/background/BackgroundMIDlet2.java, tests/midlets/background/ForegroundMIDlet.java
Reverts mozilla/j2me.js#1030 for a firstrun regression.
=> Revert "Don't wait for localmsg before starting FG MIDlet"

Makefile, tests/com/ibm/tck/client/TestRunner.java
This should help reduce the number of lines we log to Travis. We may still need reduce it more to get under 10K lines once @TimAbraldes's #1368 lands.
=> shush more stuff by default

benchmark.js
Good to known the setup that the results were created on.
=> Add more info about benchmarks to output.

midp/text_editor.js
Depends on https://github.com/mozilla/j2me.js/pull/1410.
=> Honor max length property also when the input type is 'number'

jit/baseline.ts, vm/runtime.ts
This inlines the static method lookup fast path, improves perf on some benchmarks by 30%.
=> Faster invoke static path that doesn't cause polymorphic lookups.

index.js.in, jit/analyze.ts, main.js, midp/midp.js, midp/sms.js, tests/mozactivitymock.js, tests/mozactivitymock.unprivileged.js
It needs to happen in the privileged context.
=> Fix MozActivity usage

java/custom/com/nokia/mid/ui/lcdui/DisplayStateListener.java
DisplayStateListener is supposed to be an interface.
=> Make DisplayStateListener an interface

README.md, benchmark.js
I also updated the docs and corrected a few grammar nits in the process.
=> replace INSIGNIFICANT with SAME to reduce benchmark results table width

vm/runtime.ts
This PR cherry picks the interface dispatch changes from #1452
=> Interface Optimization

midp/localmsg.js
This should avoid allocations in some cases and should help with #1133.
=> Add LocalMsgConnectionMessage class

benchmark.js
=> Revert "Add USS and peakRSS values to the startup benchmark"

libs/fs.js, main.html.in, main.js
I don't like buttons that don't give feeback.
=> Log completion of file system deletion.

bench/SocketBench.java
> 5:33:37 PM - myk: marco: sounds good; i haven't tested my socket branch much lately, but i suspect it doesn't do much either, or even makes the problem worse
> 5:34:13 PM - marco: myk: I think the benchmark from the PR could be merged
> 5:34:28 PM - marco: myk: if you want, create a new PR that only adds the benchmark and merge it yourself
> 5:35:01 PM - myk: marco: ok, will do
=> add benchmark for Socket API

midp/gfx.js, midp/midp.js
This applies over #1513 and #1514
=> Move fullscreen management from gfx to midp

README.md
address bug #1530, add install/cold/warm diagram
=> address bug #1530, add install/cold/warm diagram

midp/gfx.js, midp/midp.js, midp/sensor.js, midp/text_editor.js
=> Implement refresh0.

tools/benchrunner/benchrunner.js
fix indenting of benchrunner, remove duplicate code, better promises coding style
=> bench runner script improvements

main.js, vm/context.ts
From:
```
Timeline Statistics: 0
Timeline Statistics: 1
Timeline Statistics: 2
Timeline Statistics: 3
Timeline Events: 0
Timeline Events: 1
Timeline Events: 2
Timeline Events: 3
```
To:
```
Timeline Statistics: Threads
Timeline Statistics: Runtime
Timeline Statistics: Thread: 0:0
Timeline Statistics: Thread: 1:1
Timeline Events: Threads
Timeline Events: Runtime
Timeline Events: Thread: 0:0
Timeline Events: Thread: 1:1
```
=> give text profile section titles descriptive names

Makefile, bindings.ts.in, config/runtests.js, jsshell.js, midp/content.js, midp/midp.js, tests/javax/microedition/content/TestContentHandler.java, tests/native.js, tests/runtests.jad
This PR is implementing the content handler natives and adding a few simple tests for them.
The only missing part is hooking them up to MozActivity, which I'll do in a followup.
=> Implement content handler natives

bench/BouncyCastleSHA256.java, bench/lcrypto-j2me-152/LICENSE.html, bench/lcrypto-j2me-152/src/org/bouncycastle/crypto/Digest.java, bench/lcrypto-j2me-152/src/org/bouncycastle/crypto/ExtendedDigest.java, bench/lcrypto-j2me-152/src/org/bouncycastle/crypto/digests/EncodableDigest.java, bench/lcrypto-j2me-152/src/org/bouncycastle/crypto/digests/GeneralDigest.java, bench/lcrypto-j2me-152/src/org/bouncycastle/crypto/digests/SHA256Digest.java, bench/lcrypto-j2me-152/src/org/bouncycastle/util/Memoable.java, bench/lcrypto-j2me-152/src/org/bouncycastle/util/Pack.java
Uses the same library as a popular midlet.
=> Add bouncy castle SHA-256 benchmark.

certs/Makefile
A helpful reminder for infrequent use of mekeytool.
=> document provenance and location of mekeytool on Mac

tests/gnu/testlet/vm/TestIsolate.java
Reverts mozilla/pluotsorbet#1684
=> Revert "Add some more checks to the TestIsolate testlet"

Makefile, README.md, tests/gnu/testlet/vm/TestIsolate.java
We need this to make tests pass again.
=> Merge master into intex

midp/content.js, midp/fs.js, midp/midp.js, midp/pim.js, midp/sensor.js, vm/context.ts, vm/runtime.ts
Depends on https://github.com/mozilla/pluotsorbet/pull/1677.
=> Make newString return addresses

README.md, int.ts, midp/background.js, midp/codec.js, midp/content.js, midp/crypto.js, midp/frameanimator.js, midp/fs.js, midp/gfx.js, midp/localmsg.js, midp/location.js, midp/media.js, midp/midp.js, midp/pim.js, midp/sensor.js, midp/sms.js, midp/socket.js, nat.ts, native.js, string.js, tests/gnu/testlet/vm/NativeTest.java, tests/javax/microedition/lcdui/TestGraphics.java, tests/native.js, vm/runtime.ts
Re-request of intex-pass-addresses branch from #1712 to address issue that caused it to be reverted in #1721. WIP until issue has been addressed.
=> pass objects/arrays to natives as addresses

Makefile, int.ts, jit/compiler.ts, jsc.ts, tests/gctests.js, tests/runtests.py, vm/context.ts, vm/native/native.cpp, vm/runtime.ts
This PR enables garbage collection for objects created via *allocObject*.
=> Enable GC for some objects

native.js, tests/gctests.js, vm/runtime.ts
=> Collect native objects

Makefile, int.ts, midp/codec.js, midp/frameanimator.js, midp/gfx.js, midp/localmsg.js, midp/socket.js, native.js, tests/gctests.js, vm/context.ts, vm/native/native.cpp, vm/runtime.ts
=> Register finalizers only when needed

bytecodes.ts, interpreter.ts, jit/analyze.ts, jit/baseline.ts, jit/blockMap.ts, options.ts, utilities.ts, vm/context.ts, vm/hashtable.ts, vm/parser.ts, vm/runtime.ts
Because "assertion failed" is almost as disheartening and unhelpful
as "Segmentation fault"
=> Require a message in assert

bindings.ts.in, int.ts, java/custom/com/sun/midp/crypto/MD5.java, jit/compiler.ts, midp/crypto.js, midp/gfx.js, midp/midp.js, midp/sensor.js, nat.ts, native.js, tests/gctests.js, tests/org/mozilla/test/ClassCast.java, vm/classRegistry.ts, vm/context.ts, vm/parser.ts, vm/runtime.ts
This is now passing tests locally with GC enabled.
=> Remove Klass

nat.ts, native.js, tests/java/lang/ref/TestWeakReference.java, vm/runtime.ts
=> Support weak references

bindings.ts.in, int.ts, java/custom/com/sun/midp/crypto/MD5.java, jit/compiler.ts, jsc.ts, jsshell.js, midp/crypto.js, midp/gfx.js, midp/midp.js, midp/sensor.js, nat.ts, native.js, tests/gctests.js, tests/org/mozilla/test/ClassCast.java, tools/lib.d.ts, util.js, vm/classRegistry.ts, vm/context.ts, vm/parser.ts, vm/runtime.ts
=> Remove util::stringToCharArray

config/default.js, config/runtests.js, config/runwhatsapppreview.js, main.js, midp/background.js, midp/sms.js, tests/automation.js, tests/index.js.in, tests/midlets/background/BackgroundMIDlet1.java, tests/midlets/background/ForegroundEnableBackgroundServiceMIDlet.java, tests/midlets/background/ForegroundSMSMIDlet.java, tests/midlets/background/destroy.jad, tests/midlets/background/foregroundEnableBackgroundService.jad, tests/midlets/background/foregroundExit.jad, tests/midlets/background/foregroundSMS.jad, tests/native.js
I'm using a simple hack: creating a file (unaccessible to MIDlets) called "smsReg".
=> [WhatsApp] Start the background alarm only after the verification process

midp/gfx.js, tools/lib.d.ts, util.js, vm/runtime.ts
This makes *fromStringAddr* faster by avoiding the indirection through *getArrayFromAddr*.
=> Improve fromStringAddr

bench/DoubleBench.java, bench/UncheckedArrayCopyBench.java, native.js.in
=> Avoid getArrayFromAddr in the unchecked_*_arraycopy natives

bench/MultiArrayBench.java, vm/runtime.ts
These changes speed up the attached microbenchmark (from ~5500 ms to ~4500 ms).
=> Optimize newMultiArray

bench/ArrayCopyBench.java, native.js.in, tests/com/sun/cldchi/jvm/TestJVM.java, tests/gnu/testlet/java/lang/System/arraycopy.java
I've spent a lot of time debugging, and it was: fea89eaf7a2cf2601e8f740500244640ef79abc7
=> Re-enable optimization for System::arraycopy

tests/automation.js
=> Synchronize FS after the first foregroundEnableBackgroundService test

Makefile, int.ts, vm/native/native.cpp, vm/runtime.ts
I still need to test this thoroughly.
=> Use Boehm's GC heuristics instead of our own

jsshell.js, nodeshell.js
```
node nodeshell.js Hello
```
=> Make it possible to run the shell in Node.

bench/SchedulerBench.java, native.js, scheduler.ts, vm/context.ts
This eliminates calls to `getPriority` and instead maintains a property
on Context objects that reflects the thread priority.
I ran the startup benchmark on two devices. 100 rounds, 25000ms delay, GC enabled.
Flame device
|         Test         | Baseline Mean |    Mean    |   +/-   |    %    |    P    |     Min    |     Max     | 
|:---------------------|--------------:|-----------:|--------:|--------:|--------:|-----------:|------------:|
| startupTime          |      16,598ms |   15,643ms |  -955ms |   -5.75 |  BETTER |   13,854ms |    18,816ms | 
| vmStartupTime        |       2,783ms |    2,606ms |  -177ms |   -6.37 |  BETTER |    2,160ms |     2,880ms | 
| bgStartupTime        |         897ms |      826ms |   -70ms |   -7.83 |  BETTER |      591ms |     1,026ms | 
| fgStartupTime …
=> Make priority a property of Context

tests/automation.js
We should be able to use the same timeout values as master.
=> Use saner timeout values

tests/automation.js, tests/gnu/testlet/DumpTestHarness.java, tests/gnu/testlet/TestHarness.java, tests/isolate/IsolatedClass.java, tests/isolate/TestIsolate.java
Started this awhile ago and needed it again in another PR.
It should test nearly all the same things as the old one except it only verifies that the isolate id's increase, not that they are specific value.
=> Use a more predicable isolate test with assertions.
