native.js
If class `A` imports a missing class `B`, `Class.forName("A")` will report `A` is not found exception other than `B` is not found.
This patch fixes this and let `Class.forName` report correct name of `ClassNotFoundException`.
=> Class.forName should reports the correct name of ClassNotFoundException

java/cldc1.1.1/com/sun/cldc/i18n/uclc/DefaultCaseConverter.java, native.js, override.js, tests/RunTests.java, tests/automation.js, tests/gnu/testlet/java/lang/Long/new_Long.java
j2me divides all characters into 3 groups: 
1. lowercase, such as `a`, `b`, ...
2. uppercase, such as `A`, `B`, ...
3. others, such as `;`, `你`, ...
The characters from the 3rd group are not case sensitive, such as punctuation symbols. They doesn't fall into either the lowercase or uppercase group. So calling `isLowerCase()` and `isUpperCase()` over these characters should always return false.
But commit 76801f1c669a9a7 modified the original methods and made `isLowerCase()` and `isUpperCase()` return true over these case insensitive characters.
I reverted the changes to `isLowerCase()` and `isUpperCase()` to recover the original behavior.
=> Fix isLowerCase and isLowerCase bug.

.travis.yml
Switching to the [new container-based infrastructure](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) on Travis should make our builds faster. Currently, they tend to take over five minutes, like this recent one that took 5 min 14 sec:
https://travis-ci.org/andreasgal/j2me.js/builds/46750116
Whereas the build for this change to use the container-based infrastructure took 4 min 13 sec:
https://travis-ci.org/mykmelez/j2me.js/builds/46799276
=> switch to new container-based infrastructure

.travis.yml
Now that we're using Travis's container-based infrastructure, we can cache some dependencies. This change caches local node modules and the SlimerJS/XULRunner packages (both of which it now downloads to */tmp/j2me.js/*, since Travis can only cache arbitrary directories, not arbitrary individual files).
(We might also be able to cache the SlimerJS/XULRunner installations, but I'd have to think through that more carefully, since "installation" of those packages is currently just unzip/tar, which might not update the installations correctly when the packages get updated.)
Here's the first build with this change, where you can see the cache being created:
https://travis-ci.org/mykmelez/j2me.js/builds/46804315
And here's an empty change I pushed so you can see it being restored and used: …
=> cache node modules and SlimerJS/XULRunner packages (fixes #847)

classinfo.js, index.html, index.js, instrument.js, jsshell.js, libs/console.js, libs/urlparams.js, main.html, main.js, manifest.webapp, midlet.js, midp/gfx.js, midp/midp.js, native.js
Unfortunately, the Marketplace validator rejects query parameters in launch paths because of [bug 943710](https://bugzilla.mozilla.org/show_bug.cgi?id=943710), so this makes them configurable via a *config* Object defined in midlet.js.
It isn't entirely functionally equivalent, since the query parameters allow us to specify parameters that only apply when the app is installed as an app (as opposed to being loaded in the browser). But it's close enough.
I've tested and confirmed that I can configure the project for a midlet, package it, run the midlet on a device as before, and pass validation on Marketplace.
=> move configuration from launch path params to midlet.js

midp/text_editor.js
A fix to text editor to support Chinese input. It also enables to use cut and paste on firefox desktop.
We use `oninput` to monitor the changes of the editor's HTML content and updates the emoji images inside.
=> To support Chinese input. #835

midp/gfx.js
In the common case, when there no emojis in the string and there's no horizontal anchor, we don't need to measure the string width.
=> Measure string width only if necessary

midp/gfx.js, native.js
Since dechameleonization, FormLFImpl and ItemLFImpl natives output a gazillion "not implemented" warnings, which pegs the log limit on Travis. So this branch adds an *UnimplementedNative* constructor whose instances output only a single warning, the first time they're called.
=> warn once for noisy unimplemented natives

tests/fs/automation.js
The fs automation tests tend to time out on one of my Linux VMs, presumably because that machine is slower than the host machine. I also see timeouts on the host machine when I enable fs debugging, which generates a bunch more log output. And I've still seen intermittent timeouts on Travis, although they're rarer since we bumped the wait timeout from 15 to 30 seconds.
So this branch bumps it to 60 seconds and adds a handler that dumps a screenshot URL if it still times out.
=> wait longer before timing out; dump screenshot on timeout

tests/automation.js
On Mac, these tests produce larger numbers of differing pixels because of a different font weight. For example, here's DrawStringWithEmojiTest (reference on left, my result on right):
=> bump max different pixels for emoji strings on Mac

midp/gfx.js
This PR is removing the callback arguments from withClip, withAnchor, withTextAnchor, withOpaquePixel, withPixel, withSize, withGraphics.
The flickering I was experiencing with a MIDlet seems to be gone after this changeset.
It might be easier to review one commit at a time, but the changes are straightforward overall.
=> Remove gfx closures

index.js, jit/analyze.ts, midp/midp.js, runtime.ts, tests/midlets/jaddownloader/AMIDletUpdater.java, utilities.ts
On Firefox OS, the app could be closed by calling `window.close()` from index.html. On desktop, unless the the app window is opened by `window.open`, we could not close the app window and nothing happens.
A few missing native methods are added to avoid error when app exits.
The previous implementation suppressed `missing native method` exceptions and it causes weird issues, such as the app hangs during exiting. I changes the implementation to throw these exceptions to let us discover such kinds of bugs earlier.
=> Allow app to exit

interpreter.ts
We ran into the case where invokevirtual triggered one virtual method that was not synchronized and other was. When the first one was not sync we patched it with a resolved invoke, which does not have the frame locking code so the second call would not trigger the lock.
=> Use slow path for synchronized methods to ensure we lock.

jit/analyze.ts
These methods are no longer async native methods and could be removed from the yield map.
=> Remove drawString, drawSubstring and drawChars from yield map.

midp/media.js
asyncImpl doesn't return a value, so it isn't necessary to return its return value in a function that calls it. There are two occurrences of this in the codebase, and this branch removes them.
=> don't return the return value of asyncImpl unnecessarily

native.js
=> If MCC and MNC are not available, return `null`

jit/baseline.ts, jit/jvm.ir.ts, runtime.ts
Class names are prefixed with `$` so we should never use anything that starts with $.
=> Rename globals to avoid collisions.

midp/midp.js
Otherwise, the JAD/JAR might not get synced to the persistent store before the app restarts.
=> after updating the JAD/JAR, sync the fs before restarting the app

midp/frameanimator.js, midp/gfx.js, midp/midp.js, native.js
This simplifies UnimplementedNative declarations by eliminating the need to hardcode the method signature twice.
=> make unimplemented native 'constructor' add itself to Native hash

context.ts, tests/automation.js, tests/javax/microedition/media/TestMediaImage.java
The wakeup() code will never(and should never) throw exceptions so we no longer need to do the setTimeout. Also, removing the block() callbacks helped with reduce allocations in chrome's memory profiler.
=> Remove un-needed callback and timeout.

main.html, polyfill/codepointat.js, polyfill/fromcodepoint.js, tools/package.sh
These are needed for FxOS 1.3. They come from these MDN pages:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt
I decided to create a new *polyfill* directory so we can distinguish between the various polyfills and libraries. We should move other polyfills there too (chrome_polyfills.js, libs/promise-6.0.0.js, etc.).
=> polyfill String.fromCodePoint and String.prototype.codePointAt for FxOS 1.3

main.html.in
@yxl: #939 accidentally enabled the profiler by default. This disables it again.
=> disable profiler

java/Makefile, java/custom/com/nokia/mid/s40/bg/BGUtils.java, tools/package.sh
1. Bumping the priority of WaitUserInteractionThread enables it to resume more quickly after the localmsg server is created, shaving up to a second off the time it takes to start the foreground midlet on my Flame.
2. The *-g:none* flag to javac removes about 300K of debugging info from classes.jar, which should save a bit of time loading that file.
3. Packaging classes.jar.js should save time due to reduced interpretation.
=> miscellaneous startup optimizations

midp/media.js
I added real type checking for native return values and found we were returning a long and trying to divide a long by 1000. Separate PR coming to add real type checking.
=> Convert long to int for setMediaTime.

index.js
Navigation in the child shouldn't happen, but this is defense in depth in case it does. Unfortunately, I can't check *event.target.origin*, as suggested in #909, because the child doesn't *postMessage* to the parent. So instead I track the child's location with *mozbrowserlocationchange* and ignore the message if the parent and child origins differ.
This one is difficult to test automatically, but I've confirmed that it works as expected with these manual test steps:
1. load some midlet in a browser tab, f.e. http://localhost:8000/index.html?midletClassName=midlets.InitMidlet&jars=tests/tests.jar
2. install [tcpsocketpup](https://github.com/mykmelez/tcpsocketpup/releases/latest) and use it to give the URL mozbrowser permissions
3. reload the tab
4. open Developer Tools and switch to the …
=> ignore messages from different origin (fixes #909)

midp/gfx.js, midp/midp.js
https://github.com/andreasgal/j2me.js/pull/966 makes canvas hold its position and not resize. It fixed the bug - black bar appears after opening text editor, but introduces two side effects when we set `autoresize=1`:
1. app, which is not in full screen, cannot display its whole content. The reason is `DisplayDevice.getScreenHeight0()` should return canvas height, but not the actual screen height. The app mistaken the screen height for the canvas height and draws out of the canvas area.
2. The system back button doesn't stay at the bottom but at the top.
The pull request reverts related changes.
As https://github.com/andreasgal/j2me.js/pull/972 already fixed the bug that causes canvas to change position and resize, so it's safe to do the reverting.
=> Fix non fullscreen display

main.html.in
The canvas looks ugly with image-rendering set to crisp-edges.
=> Don't set image-rendering to crisp-edges

midp/gfx.js
Happened to notice this while looking for something else. We should probably review all uses of innerHTML.
=> Use textContent to avoid html insertion.

jit/analyze.ts
@mbebenita found some more yielding methods that weren't marked as such (cherry picked from commit e26750f558d001cb961d2ba37b643a4427d157ae).
=> mark additional methods as yielding

manifest.webapp
This allows precompiling asm.js code at install time.
On desktop, it saves 37 ms for relooper and 1 ms for rusha, on device it's probably more than that.
=> Precompile asm.js code

libs/console.js
This adds the context ID to the messages on the Web Console in addition to the in-page console. Note that you have to set the *logConsole* parameter to something other than simply `web` in order for this to work, as the simple value `web` causes the console object to hook itself directly to the Web Console, bypassing the code that formats the message with the ID prefix.
For example, you could set *logConsole* to `web,native`. In which case you'll need the second fix in this patch, which makes the native console logger call *dump* instead of the nonexistent *dumpLine*.
=> log context ID to Web Console; fix native console logging

midp/text_editor.js, style/main.css
Fix `getContentHeight()` to make it more accurate. 
There is a midlet that increases the TextEditor unlimitedly, but Nokia Asha's implementation doesn't allow that, so I set a limit of `getContentHeight()` to 130.
Also it fixes a mistake that when the type of TextEditor has changed, I forgot to set `oninputCallback` and cause TextEditorThread don't get input notification.
=> miscellaneous new text editor fixes

tests/javax/microedition/rms/TestRecordStore.java
I''ve found this while investigating a related issue.
Since we're passing this test, we shouldn't use todo but fail.
=> Replace todo with fail for a test that we are passing

midp/text_editor.js, tests/com/nokia/mid/ui/TestTextEditor.java
Fix two bugs:
1. The styled text, such as <span>ABC</span>, from copy paste will be converted to plain text before insertion.
2. The text content inserted by `TextEditor.setContent()`, `TextEditor.insert()` and so on will be escaped, such as `"<span></span>"` is escaped to `"&lt;span&gt;&lt;/span&gt;"`.
=> Fix text editor secrity issue

tests/RunTests.java
I made this to help @mbebenita debug a particular problem, but it's actually generally useful, and it doesn't push us past the magic 10,000 line limit in Travis, so I recommend we merge it.
=> always report test results per test class

libs/fs.js, midp/fs.js, tests/automation.js, tests/com/sun/midp/publickeystore/TestInputOutputStorage.java
This is a followup to #1024 that uses Int8Array in the filesystem APIs. FileConnection is funny, since it passes around bytes as ints. Thus we have to be careful to convert them back and forth.
This change also removes a common source of test failures when I'm testing locally: if *file:////prova* already exists (f.e. because I restarted tests during a run), then *TestInputOutputStorage* used to fail. But the purpose of that class is not to test for the existence of that file, it's to use that file to test the *InputStorage*/*OutputStorage* APIs. So it shouldn't fail if the file exists, it should simply recreate the file. Now it does.
=> use Int8Array in filesystem APIs

string.js
string.intern() and J2ME.newStringConstant were not using the same pool of strings which could lead to unexpected comparison results if using "==".
Unfortunately, we don't have a good test for this at the moment.
=> Use the same intern pool for compiler and interpreter.

runtime.ts
Illuminates the problem in #1049 but does not fix it for now.
=> Enable check for unwinding during static initializers.

jsc.ts
This makes it so that in midp.js, we can use things like `Promise`,
`window.setInterval`, etc
=> Remove midp.js and crypto.js from jsc.ts

tests/javax/microedition/media/TestAudioPlayer.java
This fixes test failures that I'm seeing locally on master.
=> Increase threshold for `getMediaTime`

midp/midp.js
I get the following native method error scrolling the screen sometimes:
```
Native com/sun/midp/events/NativeEventMonitor.waitForNativeEvent.(Lcom/sun/midp/events/NativeEvent;)I throws: Error: Unexpected value for target $floatParam1
```
It is caused by a type check failure. The `floatParam1` attribute of `NativeEvent` is float, but we pass a double value in `sendGestureEvent()` for the `NativeEvent` instance.
=> Ensure floatParam1 value of the native events sent by sendNativeEvent is float but not double

native.js
System.getProperty0("com.nokia.multisim.slots") should return a string rather than a number.
=> Fix System.getProperty0("com.nokia.multisim.slots") return type.

tests/automation.js
On my Ubuntu VM, TextEditorGfxTest has 1375 different pixels, although it looks correct (reference on left, actual on right):
=> tolerate more different pixels for Ubuntu

actors.ts, interpreter.ts, jit/baseline.ts, jit/blockMap.ts, jit/compiler.ts, main.js, runtime.ts
In a subsequent PR I'll also be moving classSymbols into the new aotMetaData so we only initialized classes on a per method basis.
=> Save OSR entry points for AOT code.

.travis.yml
Make the Travis bot report one line, not enter/leave, and use a notice to reduce the noise in the IRC channel. This may need a bit of massaging to make the message be succinct yet informative. Hard to tell until I see what Travis reports in the channel as a result.
=> make travis bot report one line, not enter/leave, and use a notice

midp/gfx.js
This eliminates the need for the `withGraphics` function; instead of
calling a function every time we want a context from a `Graphics`
object, we can just cache the context so it's readily available.
=> Cache context2D on `Graphics` objects

midp/gfx.js
We've been holding onto the translation (x,y) amounts and adding them to
the positions in various `Graphics` operations. Instead, let's translate
the canvas context when the `Graphics` is translated so we don't have to
include translation amounts in our own calculations.
=> Let context handle translation

.travis.yml
Per https://github.com/travis-ci/travis-ci/issues/2539#issuecomment-74608386 and https://github.com/travis-ci/travis-tasks/pull/30, this should fix the issue with IRC notices of merge commits.
=> use commit_subject so IRC notices are correct for merge commits

libs/compiled-method-cache.js
I think we can safely remove methods from the cache once we've retrieved them and we don't need to put them in the cache Map (but we only need to store them in the DB).
All the users of CompiledMethodCache are going to eval the method after *get* or before *put*, so the method is always going to be in memory (and so a method is never going to be retrieved twice or retrieved after put).
=> Some optimizations for the CompiledMethodCache

libs/pipe.js, main.html.in, midp/gfx.js, midp/midp.js, polyfill/map.js
This branch fixes a few issues on FxOS 1.1 (Gecko 18):
1. Polyfill *Map.clear* and *Map.forEach*.
2. Replace `0b*` binary literals with `parseInt(*, 2)` (not *Number.parseInt*, which also came later).
3. Update the criteria in *DumbPipe.receiveMessage* for which *postMessage* messages to ignore, as `event.source === window` for some reason, even though the messages come from the parent frame.
Regarding that last change, the primary reason we were ignoring messages when `event.source === window` was to weed out *setZeroTimeout* messages, which no longer exist now that *setZeroTimeout* is using *Promise.resolved*.
But there are still some other users of *postMessage*, particularly the promise-6.0.0.js polyfill, which we use on 1.1. So it's still useful to weed out unrelated messages. We …
=> support FxOS 1.1 via polyfills, parseInt, postMessage fixes, etc.

config/default.js, libs/fs.js, main.js, midp/fs.js, tests/config.js, tests/fs/automation.js, tests/fs/fstests.js, tests/javax/microedition/io/file/TestFileConnection.java
To save memory (and improve perf), we should completely ignore files that midlets write and never read, replacing "transient paths" with "ignored files."
=> replace transient paths with ignored files

vm/classRegistry.ts
We returned undefined, so subsequent jars weren't loaded.
=> Continue loading jars after first one is processed.

index.js.in, libs/pipe.js
The primary optimization is to do most of the work of handling a DumbPipe event in the parent frame after a timeout, to reduce the amount of time the child frame is hung (since sending the event requires opening a modal *alert*).
A secondary optimization is to remove the support for sending an event with a callback, since we don't use that anymore.
With these changes, a simple test midlet spends half as much time in *DumbPipe.runSendQueue* in my profiles. This should improve the responsiveness of midlets that use privileged APIs (f.e. for TCP sockets).
=> optimize dumb pipe

tests/javax/microedition/location/TestLocation.java
This fixes the TestLocation.java.
We had bug that `LocationListener` cannot be removed after test by calling `provider.setLocationListener` with a null value. The reason is that when we tried to  calling `provider.setLocationListener` within `LocationListener.locationUpdated`,  `provider.setLocationListener` in turn calls `LocationListener.locationUpdated` and `LocationListener.locationUpdated` calls `provider.setLocationListener` again. Then we enter an infinite loop and make the VM hang.
We could fix this simply by moving `provider.setLocationListener` out of `LocationListener.locationUpdated`.
=> Remove LocationListener after test.

main.html.in, midp/text_editor.js
This makes improvement on the TextField edtior.
It sets correct input type and [x-inputmode](https://bugzilla.mozilla.org/show_bug.cgi?id=796544) to the text field to help type numeric values, phone number, URL and email address with capitalization and suggestion supports.
=> Support input types of number, tel, email and url

native.js, tests/java/lang/TestThreadJoin.java
`Thead.join()` is used to wait for  another thread dies. It should return immediately after the target thread dies, but I found 1 second extra delay in some circumstance.
The cause of the delay is that the reference implementation uses `Object.wait()` to wait and check if the thread is alive:
```Java
public final synchronized void join() throws InterruptedException {
while (isAlive()) {
wait(1000);
}
}
```
Before terminating the thread, the [reference implementation](https://java.net/projects/phoneme/sources/svn/content/components/cldc/branches/cldc-feature-mr4-active/src/vm/share/runtime/Thread.cpp?rev=20547) will call `Object.notifyAll()` to notify all waiting thread:
```C++
void Thread::finish() {
...
// Signal waiters waiting on thread
Scheduler::notify(&receiver, true, false …
```
=> When a thread dies, wake up other waiting threads.

interpreter.ts, native.js
This makes debugging obfuscated MIDlets easier.
=> Add method signature in the stacktrace

Makefile
We no longer have a j2me.js file in the root directory and as far as I can tell nothing generates files with a `~`.
make clean keeps failing for me since I use `~` to keep folders in git repos that are globally ignored.
=> Remove obsolete make clean step.

native.js, vm/parser.ts
This was causing the canStaticInitiaizerYield function in analyze.ts to return incorrect results.
(we really need to run tests with everything compiled and compiler assertions on!)
=> Fix getting the static initializer.

tests/java/lang/TestThreadPriority.java, vm/runtime.ts
Current thread scheduler allows thread preemption when resuming an old thread from the current thread. This preemption behavior doesn't conform with the mainstream JVM at least in the following two cases:
1. When a new higher priority thread starts, it will preempt the current thread unconditionally.
2. When the current thread leaves a `synchronized` block and wakes up a higher priority thread being blocked, the higher priority thread will preempt the current thread.
The following code illustrates the above two cases.
```Java
import java.lang.*;
/* Name of the class has to be "Main" only if the class is public. */
class TestThreadPriority
{
private static String result = "Main";
static class Prioritized extends Thread {
public Prioritized() {
setPriority(Thread.MAX_PRIORITY);
}
public …
```
=> Don't allow thread preemption when resuming a thread.

vm/classRegistry.ts
The bug doesn't break anything, as far as I know, but we aren't initializing primitive array classes when we think we are, because we reference *typeName* during every iteration of the loop, but we don't set it for each iteration. Since we only dereference *primitiveTypes[i]* once, I just inlined it.
=> correctly initialize primitive array classes

bindings.ts, midp/fs.js
This cherry-picks 5e8d5db018dbcf674fa887c78d746f2ba4efee38 from @mbebenita's repository (resolving a trivial conflict with an unrelated change in the process). I've reviewed this change and will merge it.
=> Fix unsafe property access in fs.js

bench/Makefile, java/Makefile, tests/Makefile
@marco-c's #1228 pushed us over the 10k log line limit on Travis again (which we re-approached with @TimAbraldes's #1209), so this change shushes JAR creation, as @brendandahl suggested in https://github.com/mozilla/j2me.js/pull/1209#issuecomment-78088971, to get us back under it.
=> shush jar creation

benchmark.js
With firefox and no security we can now capture memory use.  Seems relatively stable with a 5000ms timer.
Creates pretty tables now:
|      Test     |   Mean   | Baseline Mean |   +/-  |   %   |       P       |    Min   |    Max   | 
|:--------------|---------:|--------------:|-------:|------:|--------------:|---------:|---------:|
| startupTime   |  1,118ms |       1,104ms |   14ms |  1.23 | INSIGNIFICANT |  1,078ms |  1,194ms | 
| totalSize     | 51,937kb |      52,452kb | -515kb | -0.98 | INSIGNIFICANT | 50,518kb | 53,287kb | 
| domSize       |    182kb |         182kb |    0kb |  0.00 | INSIGNIFICANT |    182kb |    182kb | 
| styleSize     |    419kb |         419kb |    0kb | -0.05 | INSIGNIFICANT |    419kb |    420kb | 
| jsObjectsSize | 21,190kb |      21,189kb |    1kb |  0.00 | …
=> Add memory sampling to startup benchmark.

util.js
All the util.decodeUtf8 callers are calling it with a TypedArray parameter, so we're copying the ArrayBuffer contents before decoding.
=> Don't copy the array passed to util.decodeUtf8

jit/baseline.ts, jit/blockMap.ts, vm/runtime.ts
Cherry-picked changes from #996.
For midlet startup I see no changes on desktop and device.
For the micro benchmark com.sun.midp.crypto.SHA1_Bench that touches this code path I see:
DESKTOP:
410, 429, 433
after:
197, 203, 196
FLAME
4000, 4006, 3944
after:
1741, 1739, 1964
=> Various array bounds optimizations.

libs/jarstore.js, libs/zipfile.js
The upgrade step is just deleting the old object store and creating a new one (main.js will then re-download the MIDlet JAR).
It'd be complex to migrate the old data to the new format with the *uncompressed_len* property (well, it wouldn't be difficult, but it would require either writing a new function similar to *inflate* or modifying *inflate* to work for buffers with an unknown length, so I think handling it this way is much cleaner).
=> Create ZIP buffers with the correct size right from the beginning

native.js, vm/context.ts, vm/runtime.ts
We don't currently execute more than one frame at a time in executeFrames. This gets rid of the array allocation.
=> Change executeFrames to only execute one frame.

benchmark.js
Benchmarking currently fails if you haven't disabled security, since there are two calls to *forceCollectors*, which escalates privileges, and only one of them ensures that security is disabled first. Here's the obvious fix.
=> only force collectors if without security

tests/automation.js
The "basic tests" take 60+ seconds to run now that we've added more tests, and we previously set CasperJS's *waitTimeout* to 70 seconds, so tests time out sometimes. We should increase the timeout to provide more cushion for test anomalies. This PR sets it to 90 seconds.
On the other hand: the less cushion, the more likely we are to notice perf regressions that make the tests run longer, like the one I found in #1273. So I'm a bit ambivalent about this change. If we take it, we should make sure to monitor test run times closely. Ideally, we'd graph them over time.
=> extend wait timeout for tests

.gitignore, Makefile, jsc.ts, jsshell.js, main.html.in, tests/jarstore/jarstoretests.html, tools/package.sh
This renames the build/ directory to bld/ so it won't get stripped by Gaia when j2me.js is installed onto a device via Gaia's outoftree_apps/ directory.
@mbebenita asked that we continue to build into a subdirectory (regardless of the name) to make it easier for his editor to exclude build products.
cc: @DouglasSherk so he's aware of the change.
=> rename build/ directory to bld/

benchmark.js
Fix bustage in the benchmark code by pushing memory value onto array of values instead of overwriting array with value.
=> push memory value onto array

vm/context.ts
Zeroing the length has the same effect as assigning a new array but
avoids the creation of that new array. This avoids 10s of MiBs of
allocations when running the asteroids midlet for a while.
=> Reuse the stack array in Frame.reset().

midp/gfx.js, util.js
This avoids creating 10s of MiB of garbage strings when running the
asteroids midlet for a moderate period.
=> Avoid creating intermediate strings when generating CSS color values.

benchmark.js, gc.html, gc.js, index.js.in, jit/analyze.ts, tests/native.js
I've copied what the minimize memory usage button in about:memory does. Gives much more consistent results on device.  Desktop is also more consistent but whipsaws more.
Above: There's a spike on the new way, but I seem to have got a bit unlucky on this round because I have only seen that once in many runs.
Below: Running the new code but with a 1mb allocation in main.js.
=> Use minimize memory approach and gc in new page between rounds.

Makefile
When *BENCHMARK* changes from `1` to `0`, benchmark.js is removed from the list of *MAIN_ALL_SRCS*, but that doesn't trigger a rebuild for bld/main-all.js, because the remaining files in that list haven't changed (even if the list as a whole has changed).
So *Benchmark* remains defined, which causes main.js to call *Benchmark.initUI*, which tries to access DOM elements that have meanwhile been preprocessed out of main.html, triggering an exception.
The straightforward fix is to make main-all.js depend on .checksum, so it gets rebuilt if *BENCHMARK* (or any other build configuration variable) changes.
(There may be a better fix, unsure. But in any case .checksum is our current state-of-the-art for such dependencies.)
=> rebuild main-all.js if checksum changes so it respects BENCHMARK

java/custom/javax/microedition/lcdui/Graphics.java, midp/gfx.js
`Graphics.preserveMIDPRuntimeGC` and `Graphics.restoreMIDPRuntimeGC` are
package-private to the javax.microedition.lcdui package and are not
consumed by any members of that package. It seems we can safely remove
them from the `Graphics` class.
Note that this removes the declaration as well as the implementation;
any future errors are likely to be compilation failures rather than
runtime issues.
=> Remove unused `Graphics` methods

java/custom/com/sun/cdc/io/j2me/file/Protocol.java, jit/analyze.ts, midp/fs.js
https://github.com/mozilla/j2me.js/commit/61f41ee74dac99042aabae9ab74b9c563e6b20bf improves the responsiveness of a particular interaction in a complex midlet by making some file writes asynchronous, so repeated writes on a background thread don't starve the UI thread.
Making the writes asynchronous makes the write operations themselves many times slower (even if the app can do other work in the meantime, so overall app perf doesn't suffer). https://github.com/mozilla/j2me.js/commit/e222f5e2565556941abfb5156b0878811b70cae8 claws back much of that performance by exiting *file/Protocol.ensureConnect* early if *fileHandler* is defined instead of relying on *connect* to do so, which avoids the expensive `filePath + fileName` string concatenation.
(@brendandahl's self-hosting strings branch …
=> make some file writes asynchronous, then optimize them

tests/gnu/testlet/java/lang/Math/acos.java, tests/gnu/testlet/java/lang/Math/asin.java, tests/gnu/testlet/java/lang/Math/atan.java, tests/gnu/testlet/java/lang/Math/sin.java
Perhaps we should generate the expected values for both Linux and Mac, then choose which set to use as the reference depending on which platform we're on.  But in the meantime, we shouldn't keep failing tests.  So this change disables them.
=> disable tests that are failing on Mac

vm/runtime.ts
I've noticed we're defining these variables twice in the same file.
=> Remove redefinitions of invalidChars and replaceChars

java/custom/javax/microedition/lcdui/Graphics.java, midp/gfx.js, tests/javax/microedition/lcdui/TestGraphics.java
Remove more `Graphics` methods that can't be called.
Make the native implementations of `Graphics.getMaxWidth` and
`Graphics.getMaxHeight` actually match the signature of those methods.
=> More gfx cleanup

Makefile
J2ME_OPTIMIZATIONS breaks PROFILE=1|2 for some reason, unsure why. This branch works around the problem by reverting Closure compilation of j2me.js to SIMPLE optimizations if PROFILE is set to a value that enables the profiler.
=> revert Closure compilation of j2me.js to SIMPLE optimizations to fix PROFILE

midp/sms.js
We're currently showing "4:010" when we should show "4:10".
=> Don't show '0' before '10' when there are n minutes and 10 seconds left

Makefile
J2ME_AOT_OPTIMIZATIONS breaks classes.jar.js (per #1370), so this PR enables only SIMPLE optimizations for now.
=> Only enable SIMPLE optimizations for classes.jar.js for now

interpreter.ts, native.js, vm/context.ts, vm/jvm.ts, vm/runtime.ts
Since `Frame.localBase` is always 0, there is no need to be an attribute of Frame object. Also we don't need the wrapper functions which depends on the `localBase` attribute as well.
=> remove localBase

midp/media.js
Noticed this is unused while looking into https://github.com/mozilla/j2me.js/issues/1000
=> Don't create unneeded HTMLAudioElement

bench/GraphicsBench.java, java/custom/com/sun/midp/lcdui/RepaintEventProducer.java, jit/analyze.ts, midp/gfx.js, native.js, tests/asteroids/Field.java
This prevents us from attempting to paint multiple times to the screen
when the screen can't actually keep up due to its refresh rate.
Update the asteroids test to use the accepted mechanism for doing 1
calculation per frame.
Add a benchmark test for `Graphics.drawRegion` performance.
=> Limit refresh rate to that of screen. Update tests

main.js
When increasing the circular buffers I noticed the timelines getting out of sync because of long pauses during the resets.
=> Fix issue with timelines not being in sync.

Makefile, tests/automation.js, tests/fs/automation.js, tests/runtests.py
We've exceeded the 10K log line display limit on Travis again. This should cut out ~4K lines of CasperJS logging.
=> increase default CasperJS log level to reduce logging for Travis

.gitignore, Makefile
This adds a Make target, *package*, that creates a ZIP package for distribution as a packaged app. Once #1393 lands, we might consider naming the package after the name and version of the app being packaged.
=> add make target to package app

Makefile
This makes `make package` name the ZIP after the name and version of the app being packaged.
It accommodates app names with spaces and other punctuation. I considered removing those characters, but I'm not sure it's necessary, given modern filesystems.
It also makes *package* a phony target, which it should have been in the first place.
And I experimented with putting the package into the output/ subdirectory, but then I realized a reason to keep it in the top-level directory: WebIDE itself packages the entire contents of output/ when you use it to push a packaged app to a device, so putting the package generated by `make package` into output/ would mean that it would get included in the package that WebIDE creates, effectively doubling the size of that package.
=> Name package

interpreter.ts, jit/baseline.ts
This pull request makes sure that all the frames are freed after using and I don't see significant performance regression.
|     Test    | Baseline Mean |  Mean | +/- |   %  |       P       |  Min  |  Max  | 
|:------------|--------------:|------:|----:|-----:|--------------:|------:|------:|
| startupTime |         683ms | 691ms | 7ms | 1.06 | INSIGNIFICANT | 608ms | 984ms | 
| startupTime |         683ms | 690ms | 6ms | 0.95 | INSIGNIFICANT | 610ms | 949ms | 
| startupTime |         683ms | 677ms | -7ms| -0.96| INSIGNIFICANT | 607ms | 862ms |
=> free frames as much as possible

Makefile
Makes `make package` work with a custom *PACKAGE_DIR*.
=> change to correct package dir when making package

vm/parser.ts
Short class names, like `Ab` are now used as is and not expanded to larger names as they used to because of our hashing / name mangling scheme.
=> Use short class names whenever possible.

Makefile
@brendandahl suggested this, and it seems useful when debugging. We should do it for main-all.js too, but that's trickier, since a simple *cat* of all the scripts doesn't strip the *use strict* declarations, and some of the code is non-strict.
=> don't minify scripts unless RELEASE

benchmark.js
- vmStartupTime: time to load scripts and MIDlet files (right before starting to load the BG MIDlet)
- bgStartupTime: time from the start of the BG MIDlet to the start of the FG MIDlet
- fgStartupTime: time from the start of the FG MIDlet to the point where the FG MIDlet goes in the foreground
We could break up these in even smaller values in followups.
=> In the startup benchmark, break up the startup time in several values

java/custom/com/nokia/mid/s40/bg/BGUtils.java, java/custom/com/sun/midp/main/AmsUtil.java
These commits were part of #1030, but #1030 has been backed out.
=> Directly use AmsUtil instead of going through MIDletSuiteUtils

libs/fs.js
Unfortunately I forgot to copy the benchmark results before closing the app... With 30 rounds, startup time was 1 second better (a few ms over 1 s).
=> Don't *flushAll* during startup

midp/crypto.js
We don't have a benchmark for RSA, but this is clearly a win. The same optimization for MD5 (https://github.com/mozilla/j2me.js/pull/1467) made the MD5 benchmark ~2x faster.
=> Don't create temporary strings in bytesToHexString

midp/crypto.js
This makes the MD5 benchmark ~2x faster (~280 ms -> ~120 ms).
=> Don't create temporary strings in bin2String

Makefile
Per @mbebenita in https://github.com/mozilla/j2me.js/issues/1479#issuecomment-96946383, this updates the Closure compiler. But GitHub's CDN doesn't appear to be able to handle wget's `-N` option, so downloading the new version fails if you have an existing version:
```
04-28 00:57 > make
…
wget -P build_tools -N https://github.com/mykmelez/closure-compiler/releases/download/j2me.js-v20150428/closure.jar
--2015-04-28 00:57:22--  https://github.com/mykmelez/closure-compiler/releases/download/j2me.js-v20150428/closure.jar
Resolving github.com... 192.30.252.131
Connecting to github.com|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://s3.amazonaws.com/github-cloud/releases/30269370/491a21ae-ed3f-11e4-9b4f-f420af70d4b5.jar?response-content-dis …
```
=> update closure compiler version

benchmark.js
On some platforms (for example Mac) residentUnique is unavailable.
=> Add USS and peakRSS values to the startup benchmark

.travis.yml
Specifically, 1.4.1. Since 1.5.0-beta was released today, and it's causing build failures, like https://travis-ci.org/mozilla/j2me.js/builds/60758357:
```
Building J2ME
tsc --sourcemap --target ES5 references.ts -d --out bld/j2me.js
jit/blockMap.ts(350,32): error TS2304: Cannot find name 'Map'.
jit/blockMap.ts(350,78): error TS2304: Cannot find name 'Map'.
jit/compiler.ts(206,37): error TS2304: Cannot find name 'Map'.
metrics.ts(29,22): error TS2304: Cannot find name 'Map'.
metrics.ts(95,22): error TS2304: Cannot find name 'Map'.
metrics.ts(96,21): error TS2304: Cannot find name 'Map'.
metrics.ts(97,19): error TS2304: Cannot find name 'Map'.
utilities.ts(181,40): error TS2304: Cannot find name 'Map'.
vm/classRegistry.ts(21,18): error TS2304: Cannot find name 'Map'. …
```
=> install a specific, known-good version of typescript

gc.js, index.js.in
@marco-c @brendandahl I thought this might help address #1508, but it doesn't seem to make a difference. Nevertheless, we should probably do it anyway, to avoid creating history while running the startup benchmark.
=> call location.replace to avoid creating history entry while collecting memory

midp/midp.js, style/main.css.in
Properly set the "gamepad" class on the document element when the
gamepad parameter is specified.
Fix broken CSS related to gamepad.
=> Bring back the gamepad

game-ui.js, midp/midp.js
Create an `FG` module inside of `MIDP` that keeps track of the
foreground isolate ID and the foreground display ID. Send native events
through a `FG` function so that we always properly check that the
display ID and isolate ID are valid.
Make the gamepad buttons send both press and release events. Use
mousedown and mouseup events instead of touchstart events.
Remove the unused SCREEN_REPAINT_EVENT constant.
Rename `MIDP.keyPress` and `MIDP.keyRelease` to `MIDP.send*`. This is
more consistent with other similar functions.
Remove the `MIDP.displayId` property.
=> Clean up MIDP foreground info

benchmark.js
replace calls to console.log() with an internal function
use the internal function to add a prefix to benchmark-related messages (for easier parsing of console output)
fixes issue #1546
=> add prefix to console.log messages related to Benchmark

midp/localmsg.js, tests/org/mozilla/io/TestLocalMsgProtocol.java
This race condition happens when the client tries to connect to a server that hasn't yet been created.
In this case, the server was never returning from *acceptAndOpen*.
=> Fix localmsg race condition

Makefile, README.md, main.js, midp/background.js, midp/gfx.js
This branch adds a third *PROFILE* option, `PROFILE=3`, that profiles warm startup and outputs a text file. It works on both desktop and device, and it may be able to profile warm startup even if you don't start the app in the background (although I'm not sure how accurate it is in that case).
I also updated the README to document this option and correct some obsolete information about the method timeline, which is now enabled by default.
=> profile warm startup

vm/runtime.ts
Occasionally I get in a state where a runtime compiled method is linked on the jsGlobal and then we try to link it again but since it is found on the jsGlobal it tries to link it as an AOTC method.
=> Fix linking of aot methods.

libs/compiled-method-cache.js, libs/fs.js, libs/jarstore.js, main.html.in, main.js
When you're trying to get back to the initial state of storage, it's useful to be able to blow away all three IDB databases. I think this is the most common need (and will satisfy others). You can always blow away an individual database via the console.
=> delete all three IDB databases

shumway/profiler/timelineFrame.ts
Reversing the sort order makes the most expensive methods the most prominent ones:
```
Timeline Statistics: 3
java/lang/Object.wait.(J)V: count: 1, self: 1844.965 ms, total: 1844.965 ms.
…
com/sun/midp/main/CldcMIDletSuiteLoader.startSuite.()V: count: 1, self: 0.016 ms, total: 1845.145 ms.
```
=> sort by self time descending

vm/context.ts, vm/runtime.ts
This WIP "pauses" the profiler's method timeline while a context is blocked on asynchronous resolution of a method, so it's easier to distinguish between async methods that block for a long time and methods that are themselves expensive.
WIP for cleanup, because I'd like to ponder the implementation approach a bit more, and possibly to implement aggregation of method counts/times across threads, which would make that information more useful. I may also spin off a change or two into a separate branch.
=> pause method timeline while awaiting async resolution

main.js, shumway/profiler/timelineFrame.ts
This branch reports aggregate (in addition to per-thread) method timeline statistics when PROFILE=2|3, so you can see the overall cost of methods across all the threads in which they're invoked. For example, when profiling warm startup of a complex midlet, I see that `java/lang/Object.wait.(J)V` is called from a number of different threads:
```
java/lang/Object.wait.(J)V: count: 1, self: 1961.835 ms, total: 1961.835 ms.
java/lang/Object.wait.(J)V: count: 2, self: 1956.661 ms, total: 1956.661 ms.
java/lang/Object.wait.(J)V: count: 3, self: 1102.677 ms, total: 1102.677 ms.
java/lang/Object.wait.(J)V: count: 4, self: 1141.161 ms, total: 1141.161 ms.
java/lang/Object.wait.(J)V: count: 2, self: 1827.515 ms, total: 1827.515 ms.
java/lang/Object.wait.(J)V: count: 1, self: 1961.270 ms, total: …
```
=> trace aggregate method timeline statistics

midp/localmsg.js, tests/org/mozilla/io/TestNokiaImageProcessingServer.java
Some MIDlets registered as content handlers receive an URL as invocation argument and directly pass it to the nokia.image-processing server.
(In particular, the argument is something like `url=file:///aFile`, it doesn't work without the `file:///` part, that is WA ignores it if it doesn't contain the `file:///` part)
=> nokia.image-processing fix

midp/midp.js
Warn when sending events to AMS if they have no chance of being processed. When the AMS isolate stops, update the information that we present about the AMS isolate.
This fixes issues that came up during the work on FG MIDlet launching. It's unlikely to have visible impact, but it will ease debugging if these issues come up again.
=> Create an AMS module for tracking AMS isolate

README.md, java/custom/org/mozilla/internal/Sys.java, native.js
This can be used to select a profiling window by adding calls to Sys.startProfile and Sys.stopProfile.
For example I've used it to get a profile of the first call to Canvas::paint in CanvasLFImpl.
=> Add a new customizable profiling mode

shumway/profiler/timelineBuffer.ts
*TimelineBuffer* initializes itself lazily, including creating two circular buffers (one wrapping an *Int32Array* and another wrapping a *Float64Array*). That can skew results when a method being measured by one timeline triggers the creation of another timeline, since occasionally the browser takes a while to create those typed arrays (particularly the *Float64Array* one).
In particular, when profiling a midlet that creates many threads on desktop, *Thread.start0* is one of the most expensive methods in the aggregate method statistics produced by #1569:
> java/lang/Thread.start0.()V: count: 11, self: 94.898 ms, total: 94.898 ms.
But most of the cost is because it creates a new *Context*, which creates a new *TimelineBuffer*, and then starts the context, which enters …
=> pre-allocate circular buffers to avoid expensive allocations during profiling

.travis.yml, Makefile
We're currently downloading SpiderMonkey only on Travis (via .travis.yml). Downloading it in the Makefile makes it easier for developers (for example, it'd avoid problems like https://github.com/mozilla/j2me.js/issues/1623).
=> Automatically download SpiderMonkey in build_tools

tests/sslEchoServer.py
sslEchoServer.py ignores all exceptions inside its `while True` loop, which makes it unkillable. In my testing, the only exception that actually gets thrown is indeed ignorable, but we should only ignore it for the one line that throws it, so it's possible to kill the server with a timely Ctrl+C.
=> don't ignore all exceptions, just SSLEOFError

tests/sslEchoServer.py
We need to continue if there's an error calling *ssl.wrap_socket*, otherwise *connstream* will be undefined when we try to access it, leading to error messages like this one:
>Traceback (most recent call last):
>  File "./sslEchoServer.py", line 35, in <module>
>    if (connstream):
>NameError: name 'connstream' is not defined
- https://travis-ci.org/mozilla/j2me.js/builds/66925922
=> continue instead of merely passing if error opening connstream

bench/DataInputOutputStreamBench.java, java/custom/java/io/DataInputStream.java, java/custom/java/io/DataOutputStream.java
I've noticed *readInt* and *readShort* are called many times during startup of a MIDlet. This micro-optimization improves their perf by nearly 2x.
=> Inline *read* calls in DataInputStream and *write* calls in DataOutputStream

aot-methods.txt, java/custom/java/lang/System.java, java/custom/java/lang/Thread.java
According to a profile, these functions are called a lot.
The behavior of the functions is actually left unchanged, because `AccessController::checkPermission` is a no-op (its functions are commented out, not only in our repo but also in phoneME).
*checkAccess* is taking ~18 ms during startup on my machine (which is usually more than 10x faster in CPU-bound tasks than a Flame).
*getProperty*, instead, is taking ~60 ms.
Removing these security checks allows us to remove PropertyPermission and BasicPermission methods from aot-methods.txt.
=> Remove security checks from Thread and System

README.md
This updates the README to reflect the new name of the project (and adds a reference to the trademark for JavaScript).
=> update README for new name of project

tests/httpsServer.py, tests/sslEchoServer.py
I don't recall why we specified SSLv3 in sslEchoServer.py and httpsServer.py, but tests all pass with the default SSL version (SSLv23), on Python <= 2.7.9 anyway, so it seems unnecessary to specify a different version. Here's what the [ssl.wrap_socket docs](https://docs.python.org/2/library/ssl.html#ssl.wrap_socket) have to say about it:
> The parameter ssl_version specifies which version of the SSL protocol to use. Typically, the server chooses a particular protocol version, and the client must adapt to the server’s choice. Most of the versions are not interoperable with the other versions. If not specified, the default is PROTOCOL_SSLv23; it provides the most compatibility with other versions.
Where "most compatibility" is with all SSL versions on the client, according to the chart in …
=> use the default SSL version (SSLv23) in Python test servers

tests/httpsServer.py, tests/sslEchoServer.py
Python 2.7.10 removed *RC4* from the list of SSL ciphers, but *SSLStreamConnection* only supports *SSL_RSA_WITH_RC4_128_MD5* and *SSL_RSA_EXPORT_WITH_RC4_40_MD5*, so we have to specify it explicitly in order for that class to connect to the test servers.
This does "fix #1662" ;-), but it breaks loading pages from the test servers in Firefox, which reports "An error occurred during a connection to localhost:4443. Cannot communicate securely with peer: no common encryption algorithm(s). (Error code: ssl_error_no_cypher_overlap)." So I'll probably have to expand this list, perhaps copying the default from Python (since I doesn't look like I can modify individual ciphers within it).
=> explicitly specify RC4 cipher for Python 2.7.10+ (fixes #1662)

midp/media.js
Per https://github.com/mozilla/pluotsorbet/blob/4c1ef19c3f4ddfe6092516bc3dc77bb630a97785/java/midp/com/sun/mmedia/PlayerImpl.java#L118, Java player IDs can range from 0 to 32767, so it isn't necessary to shift the isolate ID more than 15 bits in PlayerImpl.nInit to ensure native player IDs are unique.
(Nor is it useful to shift by 32 bits, since http://es5.github.io/#x11.7.1 says, "Let shiftCount be the result of masking out all but the least significant 5 bits of rnum, that is, compute rnum & 0x1F," and `32 & 0x1F` is `0`, so `n << 32 === n << 0`.)
=> shift isolate ID by minimum bits necessary to ensure native player ID uniqueness

tests/automation.js
We could probably make the maxDifferentMac numbers smaller now, since the images were produced on a Mac.
=> Update number of different pixels for AlertTest and AlertTwoCommandsTest

tests/java/lang/TestArrayMonitor.java
While running WhatsApp with https://github.com/mozilla/pluotsorbet/pull/1677 I've run into an issue related to arrays used as monitors. This test makes it easier to debug related problems.
=> Test using an array and an array of arrays as monitors

tests/automation.js
When my machine is under load, it takes more than 80 seconds for the basic unit tests to run, so they time out. This change increases the timeout to 90 seconds.
=> increase main automation test timeout

Makefile
The version of SpiderMonkey we were using, 37.0b7, seems to have disappeared from ftp.mozilla.org. The latest release from the 37 branch is 37.0.2, so let's use that instead.
=> update SpiderMonkey version for jsshell

int.ts, midp/content.js, midp/fs.js, midp/gfx.js, midp/media.js, midp/midp.js, midp/pim.js, nat.ts, native.js, tests/native.js, vm/context.ts, vm/runtime.ts
There are still three places where it's used:
- *fastInterpreterFrameAdapter*, used by natives that call getLinkedMethod;
- getfield or getstatic, because some natives set JS objects as Java properties. Removing this instance of canonicalizeRef makes WeChat fail (but not tests or WhatsApp), so there are probably just a few natives that are doing that.
- invoke*, for natives that return objects instead of addresses.
I'm submitting this PR anyways because it removes all instances of Java objects and arrays from the *ref* array (there were still a few added by getfield or getstatic).
So, after this PR, on the ref array Java objects and arrays are always represented as addresses.
=> Get rid of canonicalizeRef (almost)

README.md, benchmark.js, int.ts, midp/background.js, midp/codec.js, midp/content.js, midp/crypto.js, midp/device_control.js, midp/frameanimator.js, midp/fs.js, midp/gfx.js, midp/localmsg.js, midp/location.js, midp/media.js, midp/midp.js, midp/pim.js, midp/sensor.js, midp/sms.js, midp/socket.js, nat.ts, native.js, string.js, tests/mozactivitymock.unprivileged.js, tests/native.js
This passes the address of the *this* object as the first argument to every native function call. It doesn't yet make the interpreter stop binding natives to handles, however. Nor does it make the natives use the *addr* value to get handles (except in a few test cases in nat.ts).
This is based on top of intex-object-layout (#1659), but I can't request a pull into that branch within the https://github.com/mozilla/pluotsorbet repository, since that branch is in my personal repository, so the diff view doesn't here show an accurate set of changes.
=> pass addr to native methods

README.md, int.ts, midp/codec.js, midp/frameanimator.js, midp/fs.js, midp/gfx.js, midp/localmsg.js, midp/midp.js, midp/socket.js, native.js, string.js
This branch removes references to the *this* object from natives. It's a followup to (and depends on) #1676.
=> remove references to *this* object from natives

int.ts, nat.ts, vm/context.ts, vm/runtime.ts
This depends on #1685 and #1676.
Passing addresses to Object::wait and Object::nofify allows us to remove the "_address" property from arrays.
=> Use addresses in Object::wait and Object::notify and cleanup invoke*

int.ts, jit/compiler.ts, nat.ts, vm/parser.ts, vm/runtime.ts
There are still two test failures (tests/gnu/testlet/vm/FieldNotFoundException.java and tests/gnu/testlet/vm/MethodNotFoundException.java).
After this, we should be able to enable garbage collection.
(Depends on #1690)
=> Use i32 instead of ref

README.md, int.ts, midp/background.js, midp/codec.js, midp/content.js, midp/crypto.js, midp/frameanimator.js, midp/fs.js, midp/gfx.js, midp/localmsg.js, midp/location.js, midp/media.js, midp/midp.js, midp/pim.js, midp/sensor.js, midp/sms.js, midp/socket.js, nat.ts, native.js, string.js, tests/gnu/testlet/vm/NativeTest.java, tests/native.js, vm/runtime.ts
This changeset makes the interpreter pass objects/arrays to natives as addresses rather than handles.
To distinguish parameters that take addresses (and reduce the scope of changes), it appends "Addr" to the names of all object/array parameters and calls *getHandle* within natives to get handles as needed, frequently assigning them to a local variable with the same name as the parameter, minus the "Addr" suffix.
This changeset also replaces *fromJavaString* with *fromStringAddr* for conversion from a Java string (address) to a JS string.
In a few cases, it renames parameters to their names in the corresponding Java native method declarations. In a few cases, it inserts line breaks to limit line widths to <= 120 characters (since the "Addr" suffixes add length to already-long native method …
=> pass objects/arrays to natives as addresses

tests/httpsServer.js, tests/runtests.py, tests/sslEchoServer.js
The Python HTTPS server doesn't work on Fedora 22, so I've rewritten it in JS.
If it works on Travis and Mac, I'll rewrite the other SSL server as well.
=> Use a node.js https server

README.md, int.ts, midp/background.js, midp/codec.js, midp/content.js, midp/crypto.js, midp/frameanimator.js, midp/fs.js, midp/gfx.js, midp/localmsg.js, midp/location.js, midp/media.js, midp/midp.js, midp/pim.js, midp/sensor.js, midp/sms.js, midp/socket.js, nat.ts, native.js, string.js, tests/gnu/testlet/vm/NativeTest.java, tests/native.js, vm/runtime.ts
Reverts mozilla/pluotsorbet#1712
#1712 breaks WhatsApp and WeChat.
In WhatsApp, I see a long series of:
```
2.3:8.10 | java.lang.NullPointerException: klass is null 
2.3:8.10 |    (stack trace incomplete) 
```
In WeChat:
```
10(07-9:00:05:13:833 EDT)-e/CrashMgr:exception:java.lang.NullPointerException: getNative(...) is undefined
```
=> Revert "pass objects/arrays to natives as addresses"

index.js.in, jsc.ts, jsshell.js, libs/contact2vcard.js, libs/fs.js, libs/pipe.js, midp/localmsg.js, polyfill/chrome_polyfills.js, scheduler.ts, tests/contacts.js, tests/fs/fs-v1.js, tests/fs/fs-v2.js, tests/mozactivitymock.js, timer.js, vm/context.ts
Implement `window.nextTickDuringEvents`. This function implements a zero
timeout using `window.postMessage`, so the callbacks will be called
serially along with events during event loop processing.
Renamed `window.setZeroTimeout` to `window.nextTickBeforeEvents`. The
callbacks registered with this function are called before event
processing happens during the event loop.
The rename is because we now have two functions that accomplish a zero
timeout. They should have similar but unique/descriptive names.
=> Impl nextTickDuringEvents, rename setZeroTimeout

libs/jarstore.js, main.js, tests/automation.js
This fixes #1666, which is a regression from #1578.  Now that runtests.js sets config.jad, config.jad and config.downloadJAD are both defined during the JAD downloader tests, so main.js loads and processes both of them.
Those loads are both asynchronous, and they race each other, so the failure happens when config.jad is processed second, and its data overwrites the data processed from config.downloadJAD.
This changeset does two things to address the issue:
1. Only ever loads one of the two files, preferring config.jad, which should cause these tests to fail consistently rather than intermittently.
2. Unsets config.jad for the JAD Downloader tests, so the tests pass instead of failing.
Along the way, I noticed that *JARStore.installJAR* doesn't set JARStore's *jar* private variable, which …
=> ensure processJAD called only for jad or downloadJAD (fixes #1666)

int.ts, native.js, vm/context.ts, vm/native/native.cpp, vm/runtime.ts
This also contains code to support collecting thread stacks, but it isn't enabled yet because there's still one bug left to fix.
Depends on #1739 and #1741.
=> Allocate collectable thread objects and enable collection of thread stacks

java/custom/com/sun/midp/lcdui/RepaintEventProducer.java, jit/analyze.ts, midp/gfx.js
This way we only paint when it actually makes sense (i.e. we use
requestAnimationFrame how it was intended).
This patch removes the waitForAnimationFrame function but still accomplishes the throttling that that function intended to provide. This patch also ensures that we paint at the appropriate time. Previously we were queuing a thread for execution during the requestAnimationFrame callback, but then we weren't actually painting, so we were probably painting at inopportune times.
On my Macbook Pro, this drew smoother animations for the Asteroids MIDlet.
This is the result of the startup bench on a Flame device. 100 rounds, 25000ms delay, GC enabled:
|         Test         | Baseline Mean |    Mean    |    +/-    |    %    |     P    |     Min    |     Max     | …
=> Use requestAnimationFrame in DisplayDevice.refresh

midp/gfx.js, native.js
This simplifies the natives where we were doing *getNative(getHandle(addr)))* and stores an address as the GraphicsInfo font property.
=> Remove unneeded getNative calls

java/Makefile
In the default GNOME file manager (Nautilus), search results are organized in a list which contains the name of the file, its parent directory and some other info.
There isn't a column for the entire path (there was in a previous version), so searching for a Java file in our repo is annoying for me (because I always find multiple files and I don't know which one I should open).
Since build-src/ is a temporary directory and isn't actually needed, I'd like to remove it when the build is finished.
=> Remove build-src/ directoy when building

tests/org/mozilla/gc/TestRuntime.java
I think the problem was that we currently don't set pointers to object interiors as invalid.
Indeed, I was able to reproduce the bug on my machine if I set the size of the array to 10485760, but the bug wasn't reproducible if I merged https://github.com/mozilla/pluotsorbet/pull/1622 into my branch.
I've modified the test to make it reliable also for small allocations (so that https://github.com/mozilla/pluotsorbet/pull/1622 isn't required to make this test reliable) by forcing collections until every dead object is freed before running the test.
=> Fix TestRuntime

tests/gnu/testlet/vm/TestArithmetic.java, tests/test/org/jikesrvm/basic/bugs/R1644449.java, tests/test/org/jikesrvm/basic/bugs/R1644460.java, tests/test/org/jikesrvm/basic/bugs/R1644460_B.java, tests/test/org/jikesrvm/basic/bugs/R1657236.java, tests/test/org/jikesrvm/basic/core/bytecode/TestArrayAccess.java, tests/test/org/jikesrvm/basic/core/bytecode/TestCompare.java, tests/test/org/jikesrvm/basic/core/bytecode/TestConstants.java, tests/test/org/jikesrvm/basic/core/bytecode/TestFieldAccess.java, tests/test/org/jikesrvm/basic/core/bytecode/TestFinally.java, tests/test/org/jikesrvm/basic/core/bytecode/TestFloatingRem.java, tests/test/org/jikesrvm/basic/core/bytecode/TestInstanceOf.java, tests/test/org/jikesrvm/basic/core/bytecode/TestInvoke.java, tests/test/org/jikesrvm/basic/core/bytecode/TestResolveOnCheckcast.java, tests/test/org/jikesrvm/basic/core/bytecode/TestResolveOnInstanceof.java, tests/test/org/jikesrvm/basic/core/bytecode/TestResolveOnInvokeInterface.java, tests/test/org/jikesrvm/basic/core/bytecode/TestReturn.java, tests/test/org/jikesrvm/basic/core/bytecode/TestSwitch.java, tests/test/org/jikesrvm/basic/core/bytecode/TestThrownException.java, tests/test/org/jikesrvm/basic/core/classloading/TestClassLoading.java, tests/test/org/jikesrvm/basic/core/classloading/TestUTF8.java, tests/test/org/jikesrvm/basic/java/lang/TestMath.java
This updates the license text for files from the Jikes RVM, to which an MIT license was added recently to accommodate our use in this project: http://hg.code.sourceforge.net/p/jikesrvm/code/rev/ddd749963080.
=> update license text for files from Jikes RVM

Makefile
We're currently using 4 MB, but tests and WhatsApp are running fine with 16 kB (the stack-related assertions added by Emscripten by compiling with *-s ASSERTIONS=2* aren't failing).
=> Reduce Boehm's stack size to 16 kB

int.ts
This is the default stack size for phoneME Java threads.
phoneME employs a mechanism to grow the stack size when needed (up to 128 kB).
Looks like WhatsApp and tests are running fine with 4 kB.
While running WhatsApp, I've logged the number of threads active on the contact list screen. There are 18 threads in the first isolate and 11 in the second isolate.
Their stacks are occupying *7,25 MB* before this patch, *0,113... MB* after.
I've run the following operations in the JS console (WhatsApp, startup to the contact list, open a conversation, return to the contact list), they confirm the memory savings.
Before:
```
ASM._getUsedHeapSize()
13238272
ASM._forceCollection()
ASM._getUsedHeapSize()
9281536
```
After:
```
ASM._getUsedHeapSize()
1785856
ASM._forceCollection() …
```
=> Reduce Java threads' stack size to 4 kB

Makefile
This enables you to test against custom XULRunner installations with a Make argument:
> make test XULRUNNER=/Applications/Firefox28.app/Contents/MacOS/firefox
Unfortunately, I don't have much luck testing against other versions, at least not when using a Firefox installation as XULRunner. Various test suites (including the basic unit tests) stall and time out on older versions of Firefox, even though they run fine (and faster than the test timeout) in the browser itself, including on Firefox 25, Firefox 28, and Firefox 31 (the last of which should be equivalent to XULRunner 31, the default for our tests).
Meanwhile, newer versions of Firefox don't run tests at all, they simply exit immediately. On Firefox 40, that could be https://github.com/laurentj/slimerjs/pull/380, but I see it on …
=> specify custom XULRunner with XULRUNNER make argument

Makefile
@marco-c This branch updates to the newer version of the Closure Compiler in https://github.com/mykmelez/closure-compiler/tree/pluotsorbet-v20150814 (based on https://github.com/mbebenita/closure-compiler/tree/master). It throws these errors on the basic unit tests:
> ReferenceError: $jscomp is not defined main-all.js:12122:10
> ReferenceError: $jscomp is not defined main-all.js:4392:14
=> update to newer version of Closure Compiler

bench/ArrayCopyBench.java, native.js.in, tests/gnu/testlet/java/lang/System/arraycopy.java
The attached benchmark is almost 2x faster with these changes (I've tested it in the JS shell with RELEASE=0, because RELEASE=1 is broken in the shell).
=> Optimize System::arraycopy

Makefile, runwhatsapppreview.mk, vm/native/native.cpp
This should improve startup time.
In my testing for WA, the heap size right after startup is 2285568 bytes (often it is 1658880 bytes, but I wouldn't expect the difference to matter much). It never grows to more than 3 MB, so I've set ASMJS_TOTAL_MEMORY to 4 MB for WA (the error that occurs when the memory isn't enough is pretty clear, so we can increase it easily if needed).
=> Set GC_INITIAL_HEAP_SIZE for WA and reduce ASMJS_TOTAL_MEMORY

main.js, tests/automation.js
Since #1737, if you specify both *jad* and *downloadJAD*, *jad* takes precedence. But *jad* is set to tests/runtests.jad by default (in config/runtests.js, which is the default value of *CONFIG* in Makefile). So if you |make| and then specify *downloadJAD* in a URL parameter, it'll be ignored, which is why @brendandahl and I have been having trouble loading midlets via URLs like http://localhost:8000/index.html?downloadJAD=….
This change makes *downloadJAD* take precedence over *jad*, so URLs like that work as before. The automation.js changes simply undo a workaround for the problem when loading test URLs that relied on downloadJAD (which I completely forgot about, otherwise the problem would have been more obvious).
=> make downloadJAD take precedence to jad

int.ts, vm/parser.ts, vm/runtime.ts
This branch reenables the compiled method cache, using hashes for ClassInfo and MethodInfo IDs to maintain their stability across runs. The cache reduces startup time significantly relative to compilation without caching:
|         Test         | Baseline Mean |     Mean    |     +/-     |     %    |     P    |      Min     |      Max      | 
|:---------------------|--------------:|------------:|------------:|---------:|---------:|-------------:|--------------:|
| startupTime          |       1,265ms |       976ms |      -289ms |   -22.86 |   BETTER |        964ms |       1,008ms | 
| vmStartupTime        |         212ms |       206ms |        -6ms |    -3.02 |     SAME |        186ms |         243ms | 
| bgStartupTime        |          52ms |        43ms |        -9ms |   -17.10 | …
=> reenable compiled method cache

tests/automation.js, tests/com/sun/midp/crypto/TestBouncyCastleSHA256.java, tests/com/sun/midp/crypto/TestClasspathSHA256.java, vm/runtime.ts
With #1828, the compiler should be ready to enable on the intex branch. This branch does so.
It also increases *FREE_MEMORY_TARGET* to 4MiB as I noticed that WhatsApp was OOMing when it was set to 2MiB or less. We could use more insight into which code is allocating memory, and in what chunks. But this works for now.
=> enable compiler on intex branch

bench/All.java, int.ts, jit/baseline.ts, jsshell.js, utilities.ts, vm/classRegistry.ts, vm/parser.ts, vm/runtime.ts
This backs out some of the previous work on code caching, applies some optimizations that I had in my previews patch queue and then re-lands code caching but using relocatable JIT code instead of trying to come up with unique class ids.
=> Relocatable JIT Code

tests/org/mozilla/io/TestLocalMsgProtocol.java
TestLocalMsgProtocol has some logic that looks like this:
synchronized (someLockObject) {
someFlag = true;
someLockObject.notifyAll();
}
someBlockingFunctionThatMakesFlagActuallyTrue();
That's clearly a race condition, as the condition flag is set before the
condition is actually true. If we're relying on timing here, we're
giving ourselves a false sense of security.
Additionally, TestLocalMsgProtocol uses wait-loops to wait for
connections to be opened. However, it also opens those connections on
separate threads, so the wait-loops are unnecessary because we can just
`join` on the thread that creates the connection.
Fixes #1782
=> Fix race conditions in TestLocalMsgProtocol.

int.ts
I don't think this is being used anymore, and tests pass without it, but requesting a pull so someone else can confirm. @brendandahl or @mbebenita?
=> remove obsolete methodInfo property

libs/fs-init.js, libs/fs.js, main.js, tests/fs/automation.js
I think the TCK FileConnection tests fail sometimes because there's a race between two fs.init promise handlers: first, in fs-init.js, which mkdirs /tcktestdir after fs.init; and second, in fstests.js, which calls fs.clear after fs.init.
When fstests.js clears the database before fs-init.js creates /tcktestdir, then that directory exists, and the FileConnection tests pass.  But when fstests.js clears the database *after* fs-init.js creates /tcktestdir, then that directory gets deleted after being created, so it doesn't exist when the FileConnection tests are run, and they fail.
This branch explicitly creates /tcktestdir if we're running the FileConnection tests.  It also explicitly deletes the database before running those tests, so it should lead to more consistent success (or failure!) …
=> ensure /tcktestdir created for FileConnection tests
